# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/INST_SRAM/INST_SRAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==INST_SRAM || ORIG_REF_NAME==INST_SRAM} -quiet] -quiet
