# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/WeChat Files/wxid_7qg360e9m44722/FileStorage/File/2021-01/BNNProcessor/BNNProcessor.srcs/sources_1/ip/INST_SRAM/INST_SRAM.xci
# IP: The module: 'INST_SRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WeChat Files/wxid_7qg360e9m44722/FileStorage/File/2021-01/BNNProcessor/BNNProcessor.srcs/sources_1/ip/INST_SRAM/INST_SRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INST_SRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/WeChat Files/wxid_7qg360e9m44722/FileStorage/File/2021-01/BNNProcessor/BNNProcessor.srcs/sources_1/ip/INST_SRAM/INST_SRAM.xci
# IP: The module: 'INST_SRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/WeChat Files/wxid_7qg360e9m44722/FileStorage/File/2021-01/BNNProcessor/BNNProcessor.srcs/sources_1/ip/INST_SRAM/INST_SRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INST_SRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
